services:
  - type: web
    name: MedoBot
    env: python
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y tesseract-ocr
      pip install -r requirements.txt
    startCommand: streamlit run medobot.py
