services:
  - type: web
    name: MedoBot
    env: python
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y tesseract-ocr
      sudo ln -s /usr/bin/tesseract /usr/local/bin/tesseract
      pip install -r requirements.txt
    startCommand: streamlit run medobot.py
